/** artgen engine: TS, ESM, no Node or DOM imports. */
export const name = 'artgen-core';

export * from './lib/color.ts';
export { Grid } from './lib/grid.ts';
export { rng, hashString } from './lib/rng.ts';
export { encodePNG, decodePNG } from './lib/png.ts';
export * from './lib/palette.ts';
export { drawText, textWidth } from './lib/font.ts';
export * as post from './lib/post.ts';
export * as prim from './lib/prim.ts';
export * as blit from './lib/blit.ts';
export * as iso from './lib/iso.ts';
export * as voxel from './lib/voxel.ts';
export { initSvg, svgReady, rasterizeSvg, svgToGrid, doc } from './lib/svg.ts';
export * from './direction.ts';
export * from './render.ts';
export * from './qa/metrics.ts';
export * from './qa/conformance.ts';
export * from './qa/sheet.ts';
export * from './qa/ledger.ts';
export * from './pipeline.ts';
export * as geom from './t2/geom.ts';
export { Scene2D, type Spec, type Scene2DOptions, type Shade } from './t2/scene.ts';
export { Scene3D, type Spec3, type Render3DOptions } from './t2/scene3d.ts';
export { Raster, bandIndices, type RasterItem } from './t2/raster.ts';
export { Proc, LAYERS, valueNoise } from './t2/proc.ts';
export { applyFinish, finishSnapshot, finishStale, makePx, type FinishModule, type FinishContext, type PatchRecord, type Px } from './t2/finish.ts';
export { resolveParams, paramSchema, paramDefault, type ParamSpec } from './t2/params.ts';
export * from './w1/candidates.ts';
export { styleTile, styleSheet, wrap, paletteLuma, type ProbeImages, type StyleTileColumn } from './w1/sheets.ts';
export * from './w2/briefs.ts';
export * from './w2/status.ts';
export * from './w2/pack.ts';
export * from './w2/contract.ts';
export * from './w2/roster.ts';
export * from './w2/analytics.ts';
export * from './w2/edit.ts';
