// Generated by `artgen export` — do not edit. Typed ids for the exported art packs.

export const Packs = {
  main: "/assets/main/pack.json",
} as const;

export const Assets = {
  ghoul: { id: "ghoul", pack: "main", kind: "creature", states: ["idle","walk"], facings: ["s","sw","w","nw","n","ne","e","se"], variants: ["base"] },
  orderly: { id: "orderly", pack: "main", kind: "character", states: ["idle"], facings: ["s"], variants: ["base"] },
  rat: { id: "rat", pack: "main", kind: "creature", states: ["idle"], facings: ["s"], variants: ["base"] },
  "lamp-flicker": { id: "lamp-flicker", pack: "main", kind: "effect", states: ["idle"], facings: ["s"], variants: ["base"] },
  "iron-bed": { id: "iron-bed", pack: "main", kind: "prop", states: ["idle"], facings: ["s"], variants: ["base"] },
  "iv-stand": { id: "iv-stand", pack: "main", kind: "prop", states: ["idle"], facings: ["s"], variants: ["base"] },
  wheelchair: { id: "wheelchair", pack: "main", kind: "prop", states: ["idle"], facings: ["s"], variants: ["base"] },
  linoleum: { id: "linoleum", pack: "main", kind: "tile", states: ["idle"], facings: ["s"], variants: ["base"] },
  "ward-wall": { id: "ward-wall", pack: "main", kind: "texture", states: ["idle"], facings: ["s"], variants: ["base"] },
  "pill-bottle": { id: "pill-bottle", pack: "main", kind: "ui-icon", states: ["idle"], facings: ["s"], variants: ["base"] },
} as const;

export type AssetId = keyof typeof Assets;
export type StateOf<K extends AssetId> = (typeof Assets)[K]['states'][number];
export type VariantOf<K extends AssetId> = (typeof Assets)[K]['variants'][number];
